import {
  ActivitySquare,
  Bell,
  Building2,
  ClipboardList,
  DoorOpen,
  FileText,
  LayoutDashboard,
  LayoutGrid,
  MapPin,
  Newspaper,
  Package,
  PhoneCall,
  Shield,
  Users,
  Vote,
} from 'lucide-react'
import type { NavSection } from '@/types/navigation'

export const navigation: NavSection[] = [
  {
    label: 'General',
    items: [
      {
        to: '/app/overview',
        label: 'Overview',
        description: 'Estado general del conjunto',
        icon: LayoutDashboard,
        keywords: ['dashboard', 'inicio', 'panel'],
        roles: ['employee'],
        employeeRoles: ['administrator', 'porter', 'pool_attendant'],
      },
    ],
  },
  {
    label: 'Administracion',
    items: [
      {
        to: '/app/assemblies',
        label: 'Asambleas',
        description: 'Convocatorias y votaciones del conjunto',
        icon: Vote,
        keywords: ['asamblea', 'votacion', 'quorum', 'elecciones'],
        roles: ['employee'],
        employeeRoles: ['administrator'],
      },
      {
        to: '/app/reservations',
        label: 'Reservas',
        description: 'Areas comunes y aprobaciones',
        icon: ClipboardList,
        keywords: ['areas', 'aprobaciones'],
        roles: ['employee'],
        employeeRoles: ['administrator'],
      },
      {
        to: '/app/notifications',
        label: 'Notificaciones',
        description: 'Mensajes y avisos para residentes',
        icon: Bell,
        keywords: ['avisos', 'mensajes', 'residentes'],
        roles: ['employee'],
        employeeRoles: ['administrator'],
      },
      {
        to: '/app/calls/history',
        label: 'Historial Llamadas',
        description: 'Seguimiento y auditoría de llamadas',
        icon: PhoneCall,
        keywords: ['llamadas', 'historial', 'porteria'],
        roles: ['employee'],
        employeeRoles: ['administrator', 'porter'],
      },
      {
        to: '/app/news',
        label: 'Noticias',
        description: 'Publicaciones y comunicados del conjunto',
        icon: Newspaper,
        keywords: ['noticias', 'comunicados', 'publicaciones'],
        roles: ['employee'],
        employeeRoles: ['administrator'],
      },
      {
        to: '/app/residents',
        label: 'Residentes',
        description: 'Gestion de residentes',
        icon: Users,
        keywords: ['residentes', 'usuarios'],
        roles: ['employee'],
        employeeRoles: ['administrator'],
      },
      {
        to: '/app/employees',
        label: 'Equipo',
        description: 'Control de personal',
        icon: Shield,
        keywords: ['empleados', 'staff'],
        roles: ['employee'],
        employeeRoles: ['administrator'],
      },
      {
        to: '/app/apartments',
        label: 'Apartamentos',
        description: 'Inventario y estado',
        icon: Building2,
        keywords: ['torres', 'apartamentos', 'unidades'],
        roles: ['employee'],
        employeeRoles: ['administrator'],
      },
      {
        to: '/app/community-spaces',
        label: 'Zonas Comunes',
        description: 'Espacios de uso libre sin reserva',
        icon: MapPin,
        keywords: ['zonas', 'comunes', 'parque', 'cancha'],
        roles: ['employee'],
        employeeRoles: ['administrator'],
      },
    ],
  },
  {
    label: 'Operacion',
    items: [
      {
        to: '/app/building',
        label: 'Plano',
        description: 'Mapa visual de torres y apartamentos',
        icon: LayoutGrid,
        keywords: ['plano', 'mapa', 'torres', 'edificio', 'pisos'],
        roles: ['employee'],
        employeeRoles: ['administrator', 'porter', 'pool_attendant'],
      },
      {
        to: '/app/access',
        label: 'Accesos',
        description: 'Visitantes y entradas',
        icon: DoorOpen,
        keywords: ['porteria', 'visitantes'],
        roles: ['employee'],
        employeeRoles: ['administrator', 'porter'],
      },
      {
        to: '/app/fines',
        label: 'Multas',
        description: 'Asignación y administración',
        icon: FileText,
        keywords: ['multas', 'sanciones', 'comparendos'],
        roles: ['employee'],
        employeeRoles: ['administrator', 'porter', 'pool_attendant'],
      },
      {
        to: '/app/packages',
        label: 'Paquetes',
        description: 'Recepcion y entrega',
        icon: Package,
        keywords: ['paqueteria', 'recepcion'],
        roles: ['employee'],
        employeeRoles: ['administrator', 'porter'],
      },
      {
        to: '/app/porter-lines',
        label: 'Portería Interna',
        description: 'Llamadas entre porteros disponibles',
        icon: PhoneCall,
        keywords: ['porter', 'porteria', 'llamadas', 'interna'],
        roles: ['employee'],
        employeeRoles: ['porter'],
      },
    ],
  },
  {
    label: 'Piscina',
    items: [
      {
        to: '/app/pool/control',
        label: 'Control',
        description: 'Registro operativo de nuevos ingresos',
        icon: ActivitySquare,
        keywords: ['piscina', 'ingresos', 'control'],
        roles: ['employee'],
        employeeRoles: ['administrator', 'pool_attendant'],
      },
      {
        to: '/app/pool/reports',
        label: 'Reportes',
        description: 'Exportación PDF y parámetros del reporte',
        icon: FileText,
        keywords: ['piscina', 'pdf', 'reportes'],
        roles: ['employee'],
        employeeRoles: ['administrator', 'pool_attendant'],
      },
    ],
  },
]
